---

ssl_certificate: "ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;"
ssl_certificate_key: "ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;"
ssl: ssl
source: ../template/sitename.conf.j2
domain: "{{ inventory_hostname.split('.')[0] }}.uberlegenheit.ru"
