---

- name: Installing nginx and certbot
  ansible.builtin.apt:
    pkg:
    - nginx
    - certbot
    state: present
    update_cache: true

- name: Check if there are any certificates at all
  ansible.builtin.stat:
    path: "{{ certificate_path }}"
  register: cert_state

- name: Establishing the fact of absence or presence of certificates
  ansible.builtin.set_fact:
    is_ssl: "{{ cert_state.stat.exists }}"
  
