---

- name: Installing Nginx server
  hosts: all
  gather_facts: true
  gather_subset: [all, virtual]
  vars:
    server: "{{ inventory_hostname }}"
    email: "root@rooted.onion"
    cli_certbot_path: "/etc/letsencrypt/cli.ini"

  vars_files:
    - "vars/{{ server }}.yml"

  tasks:

    - name: Обновление системы
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Убедиться что нжинкс последней версии
      ansible.builtin.apt:
        name: nginx
        state: present
        install_recommends: true
        allow_downgrade: false

    - name: Основной конфиг нжинкс
      ansible.builtin.copy:
        src: files/uberserver/nginx/nginx.conf
        dest: /etc/nginx/

    - name: Установка конфига нжинкс
      ansible.builtin.copy:
        src: files/uberserver/nginx/sites-available/sitename.conf
        dest: /etc/nginx/sites-available/
        mode: '644'
        owner: root
        group: root
        # форсируем, чтобы затереть дефолтные конфиги.

    - name: Деплой сайта
      ansible.builtin.copy:
        src: files/uberserver/nginx/var/www/html/
        dest: /var/www/html/
        mode: '644'
        owner: root
        group: root

    - name: Удалить дефолтный симлинк
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Создать симлинк на рабочий сайт
      ansible.builtin.file:
        src: /etc/nginx/sites-available/sitename.conf
        dest: /etc/nginx/sites-enabled/sitename.conf
        mode: '644'
        owner: root
        group: root
        state: link

    - name: Установка certbot
      ansible.builtin.apt:
        name: python3-certbot-nginx
        state: present
        install_recommends: true
    
    - name: Всеотец
      ansible.builtin.shell: 
        cmd: 'certbot certonly --nginx --email {{ email }} --agree-tos --non-interactive -d "{{ domain }}"'
      register: certbot_output

    - name: Вывод сертбота
      ansible.builtin.debug:
        var: certbot_output.results

    - name: Копирование systemd демонов сертбота
      ansible.builtin.copy:
        src: /home/northernblow/prog/vm-setup/files/uberserver/systemd/
        dest: /etc/systemd/system/
        mode: '644'
        owner: root
        group: root
        force: true

    - name: Запуск демонов сертбота
      ansible.builtin.service:
        name: certbot-semi-automatic
        enabled: true
        state: started

    - name: Запуск таймера сертбота
      ansible.builtin.service:
        name: certbot-semi-automatic.timer
        enabled: true
        state: started

    - name: Перезагрузить нжинкс для применения конфигурации
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Убедиться что нжинкс стартанул
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
