---

- name: Installing Nginx server
  hosts: all
  tasks:

    - name: Обновление системы
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Убедиться что нжинкс последней версии
      ansible.builtin.apt:
        name: nginx
        state: present
        install_recommends: true
        allow_downgrade: false

    - name: Установка конфига нжинкс
      ansible.builtin.copy:
        src: src/uberserver/nginx/sites-available/sitename.conf
        dst: /etc/nginx/sites-available/
        mode: '644'
        owner: root
        group: root
        # форсируем, чтобы затереть дефолтные конфиги.
        force: true
        notify: restart nginx

    - name: Создать симлинк на рабочий сайт
      ansible.builtin.file:
        src: /etc/nginx/sites-available/sitename.conf
        dst: /etc/nginx/sites-enabled/sitename.conf
        state: link
        force: false

    - name: Перезагрузить нжинкс для применения конфигурации
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: УБедиться что нжинкс стартанул
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
