---

- hosts: webservers
  serial: 1



  roles: 
    - nginx




- hosts: vpnservers
  serial: 2

  pre_tasks:
  - name: grab info about nginx
    include_role:
      name: info
  

  roles: 
    - nginx
    - createfiles


 


