---

- name: Installing Nginx server
  hosts: all
  gather_facts: true
  gather_subset: [all, virtual]
  no_log: false
  vars:
    server: "{{ inventory_hostname }}"
    email: "root@rooted.onion"
    certificate_path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
    # is_ssl: "{{ lookup('file', '/etc/letsencrypt/live/{{ domain }}/fullchain.pem') }}"

  vars_files:
    - vars/common.yml
    - "vars/{{ inventory_hostname if molecule_file is not defined else 'molecule' }}.yml"

  tasks:

    - name: Test inventory_hostname
      debug:
        msg: 'vars/{{ inventory_hostname }}.yml'
    
    - name: Test certificate_path
      debug:
        msg: "{{ certificate_path }}"

    - name: Installing nginx and certbot
      apt:
        pkg:
          - nginx
          - certbot
        state: present
        update_cache: true

    - name: Check if there are any certificates at all
      stat:
        path: "{{ certificate_path }}"
      register: cert_state

    - name: Establishing the fact of absence or presence of certificates
      set_fact:
        is_ssl: "{{ cert_state.stat.exists }}"

    - name: Base nginx config
      copy:
        src: files/uberserver/nginx/nginx.conf
        dest: /etc/nginx/

    - name: Installing nginx configs for the sites
      template:
        #        src: files/{{ server }}/nginx/sites-available/sitename.conf
        src: "{{ source }}"
        dest: /etc/nginx/sites-available/sitename.conf
        mode: '644'
        owner: root
        group: root
      vars:
        is_ssl: "{{ is_ssl != '' }}"
        tags: molecule-idempotence-notest

    - name: debug
      debug:
        msg: "{{ source }}"

    - name: Deploy site
      copy:
        src: files/uberserver/nginx/var/www/html/
        dest: /var/www/html/
        mode: '644'
        owner: root
        group: root

    - name: Delete default symlink
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Define symlink on the sites-available
      file:
        src: /etc/nginx/sites-available/sitename.conf
        dest: /etc/nginx/sites-enabled/sitename.conf
        mode: '644'
        owner: root
        group: root
        state: link

    - name: Forced restart of njinx
      service:
        name: nginx
        state: restarted
        tags: molecule-idempotence-notest
   
    - name: Creator
      shell: 
        cmd: 'certbot certonly --webroot -w /var/www/html/ --email {{ email }} --agree-tos --non-interactive -d {{ domain }}'
      register: certbot_output
      notify:
        - restart nginx
      tags: molecule-notest

    - name: certbot's output
      debug:
        var: certbot_output.results
      tags: molecule-notest

    - name: Redefine the variable is_ssl
      set_fact:
        is_ssl: true

    - name: Redirect and 443 port
      template:
        src: "{{ source }}"
        dest: /etc/nginx/sites-available/sitename.conf
        mode: '644'
        owner: root
        group: root
        tags: molecule-idempotence-notest

    - name: Debug variable is_ssl
      debug:
        msg: "{{ is_ssl | string }}"

    - name: copying systemd demons of certbot
      copy:
        src: files/uberserver/systemd/
        dest: /etc/systemd/system/
        mode: '644'
        owner: root
        group: root
        force: true

    - name: launch its demons
      service:
        name: certbot-semi-automatic
        enabled: true
        state: started
        tags: molecule-idempotence-notest

    - name: launch certbot's timers
      service:
        name: certbot-semi-automatic.timer
        enabled: true
        state: started


    - name: Restart nginx for the apllying configuration
      service:
        name: nginx
        state: restarted
        tags: molecule-idempotence-notest

    - name: Print message
      debug:
        msg: Hello world

  handlers:
    - import_tasks: handlers/main.yml
