---

- hosts: webservers
  serial: 1



  roles: 
    - nginx




- hosts: vpnservers
  serial: 2

  pre_tasks:
  - name: grab information about nginx conf
    include_role:
      name: info
  

  roles: 
    - nginx
    - createfiles

  post_tasks:
  - name: holder
    debug:
      msg: "{{ ansible_task.name }}"


 


