---

- name: Installing Nginx server 
  hosts: all
  gather_facts: true
  gather_subset: [all, virtual]
  no_log: false
  vars:
    server: "{{ inventory_hostname }}"
    email: "root@rooted.onion"
    certificate_path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
    # is_ssl: "{{ lookup('file', '/etc/letsencrypt/live/{{ domain }}/fullchain.pem') }}"
    files_exists: "/etc/nginx/sites-available"

  vars_files:
    - vars/common.yml
    - "vars/{{ inventory_hostname if molecule_file is not defined else 'molecule' }}.yml"

  tasks:
    - name: Installing nginx server and certbot
      import_role:
        name: 'roles/nginx'

    - name: Base nginx config
      ansible.builtin.copy:
        src: files/uberserver/nginx/nginx.conf
        dest: /etc/nginx/

    - name: Installing nginx configs for the sites
      ansible.builtin.template:
        #        src: files/{{ server }}/nginx/sites-available/sitename.conf
        src: "{{ source }}"
        dest: /etc/nginx/sites-available/sitename.conf
        mode: '644'
        owner: root
        group: root
      vars:
        is_ssl: "{{ is_ssl != '' }}"
        tags: molecule-idempotence-notest

    - name: Deploy site
      ansible.builtin.copy:
        src: files/uberserver/nginx/var/www/html/
        dest: /var/www/html/
        mode: '644'
        owner: root
        group: root

    - name: Delete default symlink
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Define symlink on the sites-available
      ansible.builtin.file:
        src: /etc/nginx/sites-available/sitename.conf
        dest: /etc/nginx/sites-enabled/sitename.conf
        mode: '644'
        owner: root
        group: root
        state: link

    - name: Forced restart of njinx
      ansible.builtin.service:
        name: nginx
        state: restarted
        tags: molecule-idempotence-notest
   
    - name: Creator
      ansible.builtin.shell: 
        cmd: 'certbot certonly --webroot -w /var/www/html/ --email {{ email }} --agree-tos --non-interactive -d {{ domain }}'
      register: certbot_output
      notify:
        - restart nginx
      tags: molecule-notest

    - name: certbot's output
      ansible.builtin.debug:
        var: certbot_output.results
      tags: molecule-notest

    - name: Redefine the variable is_ssl
      ansible.builtin.set_fact:
        is_ssl: true

    - name: Redirect and 443 port
      ansible.builtin.template:
        src: "{{ source }}"
        dest: /etc/nginx/sites-available/sitename.conf
        mode: '644'
        owner: root
        group: root
        tags: molecule-idempotence-notest

    - name: copying systemd demons of certbot
      ansible.builtin.copy:
        src: files/uberserver/systemd/
        dest: /etc/systemd/system/
        mode: '644'
        owner: root
        group: root
        force: true

    - name: launch its demons
      ansible.builtin.service:
        name: certbot-semi-automatic
        enabled: true
        state: started
        tags: molecule-idempotence-notest

    - name: launch certbot's timers
      ansible.builtin.service:
        name: certbot-semi-automatic.timer
        enabled: true
        state: started


    - name: Restart nginx for the apllying configuration
      ansible.builtin.service:
        name: nginx
        state: restarted
        tags: molecule-idempotence-notest

  handlers:
    - import_tasks: handlers/main.yml
