---

- name: Creator
  ansible.builtin.shell: 
    cmd: 'certbot certonly --webroot -w /var/www/html/ --email {{ email }} --agree-tos --non-interactive -d {{ domain }}'
  register: certbot_output
  notify:
    - restart nginx
  tags: molecule-notest

- name: certbot's output
  ansible.builtin.debug:
    var: certbot_output.results
  tags: molecule-notest
